website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from .models import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    flash('Logged out Succesfully !', category='success')
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        organization = request.form.get('organization')

        password1 = request.form.get('password1')
        password2 = request.form.get('password2')


        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, last_name = last_name, organization_id = organization, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('auth.login'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, Flask, redirect, url_for, request, render_template, render_template_string
from flask_login import login_required, current_user
from sqlalchemy import func
from .models import db
import uuid
from .aws_utils import FileManagementUtils
import os

views = Blueprint('views', __name__)
aws_util = FileManagementUtils(bucket_name = os.environ.get('bucket_name'), region_name=os.environ.get('region_name'), aws_access_key_id = os.environ.get('aws_access_key_id') , aws_secret_access_key = os.environ.get('aws_secret_access_key') )

@views.route('/')
@login_required
def home():
    from .models import User

    cur_user = User.query.filter(User.id == current_user.id).first()

    return render_template('index.html', user_data = cur_user)



@views.route('/view_document/<int:document_id>')
@login_required
def view_document(document_id):
    from .aws_utils import FileManagementUtils
    from .models import Document

    doc_name =  Document.query.filter( Document.is_deleted == False ).first()

    url = aws_util.create_presigned_url(doc_name.auto_created_name, type = 'view' )

    return redirect(url)

    # return redirect(url_for("views.dashboard"))





@views.route('/download/<int:document_id>')
@login_required
def download_document(document_id):
    from .models import Document

    doc_name =  Document.query.filter_by(id = document_id).first()
    

    url = aws_util.create_presigned_url(doc_name.auto_created_name, type = 'download' )

    return redirect(url)


@views.route('/assign/<int:document_id>', methods=["GET", "POST"])
@login_required
def assign_document(document_id):
    from .models import Document , DocumentStatus,  Assignment, User

    if request.method == "GET":

        users = User.query.filter(User.organization_id == current_user.organization_id, User.id != current_user.id).with_entities(User.id, (User.first_name + ' ' + User.last_name).label('name')).all()
        documents = Document.query.join(DocumentStatus, Document.status_id==DocumentStatus.id).add_columns(Document.user_defined_name, Document.upload_date,  DocumentStatus.name  ).filter(Document.archived == False, Document.is_deleted == False, Document.id == document_id ).first()

        
        # users = User.query.filter_by(organization_id=current_user.organization_id).with_entities(User.id, (User.first_name + ' ' + User.last_name).label('name')).all()
        return render_template("assign_document_extended.html", users = users, document = documents)

    elif request.method == "POST":
        assigned_to_user_id = request.form.get('option')
        assigned_comment = request.form.get('comment')
        due_date = request.form.get('due_date')

        assigned_document = Document.query.filter(Document.archived == False, Document.is_deleted == False, Document.id == document_id ).first()
        
        new_assignment = Assignment(document_id = document_id, assigned_by_user_id = current_user.id, assigned_to_user_id = assigned_to_user_id, assigned_comment = assigned_comment, due_date = due_date, status_id = 2)

        assigned_document.status_id = 2

        db.session.add(new_assignment)

        db.session.commit()
        
        return redirect(url_for("views.assignment"))



@views.route('/review', methods = ['GET'])
@login_required
def all_reviews():
    return render_template('all_review.html')



@views.route('/review/assignation', methods = ['GET'])
@login_required
def assignation_details():
    from .models import Document , DocumentStatus,  Assignment, User

    documents = Assignment.query.join(Document, Document.id == Assignment.document_id)\
        .join(DocumentStatus, Assignment.status_id==DocumentStatus.id)\
        .join(User, Assignment.assigned_to_user_id == User.id)\
        .add_columns(Assignment.id.label('assigment_id'), Document.id, Document.user_defined_name,  DocumentStatus.name,  func.date_trunc('second', Assignment.assignment_date).label('assignment_date'),   func.concat(User.first_name, '  ', User.last_name).label('assigned_user_name') )\
        .filter(Document.archived == False, Assignment.assigned_by_user_id == current_user.id, Document.is_deleted == False ).all()

    
    return render_template('assignation_details.html', documents = zip([id for id in range(1, len(documents) + 1) ], documents))




@views.route('/review/assignation/edit/<int:assignment_id>', methods = ['GET', 'POST'])
@login_required
def assignation_details_details(assignment_id):
    from .models import Document , DocumentStatus,  Assignment, User

    if request.method == 'GET':

        users = User.query.filter(User.organization_id == current_user.organization_id, User.id != current_user.id).with_entities(User.id, (User.first_name + ' ' + User.last_name).label('name')).all()

        assigned_documents_detail = Assignment.query\
            .join(Document,  Document.id == Assignment.document_id)\
            .join(DocumentStatus, Document.status_id==DocumentStatus.id)\
            .add_columns(Document.id, Document.user_defined_name, DocumentStatus.name, Document.upload_date, Assignment.due_date, Assignment.assigned_comment, Assignment.reviewer_comment)\
            .filter(Document.archived == False, Assignment.id == assignment_id, Document.is_deleted == False ).first()
        

        default_due_date  = assigned_documents_detail.due_date.strftime("%Y-%m-%d")



        return render_template('assigned_document_edit.html', document = assigned_documents_detail, users = users, due_date = default_due_date)


    elif request.method == "POST":
        assignment_document = Assignment.query.filter(Assignment.id == assignment_id ).first()

        assignment_document.assigned_to_user_id = request.form.get('option')
        assignment_document.assigned_comment = request.form.get('comment')
        assignment_document.due_date = request.form.get('due_date')

        db.session.commit()

        return redirect(url_for("views.assignation_details"))






@views.route('/review/assigned_to_user', methods = ['GET'])
@login_required
def assignation_to_me():
    from .models import Document , DocumentStatus,  Assignment, User

    documents = Assignment.query.join(Document, Document.id == Assignment.document_id)\
        .join(DocumentStatus, Assignment.status_id==DocumentStatus.id)\
        .join(User, Assignment.assigned_by_user_id == User.id)\
        .add_columns(Assignment.id.label('assignment_id'), Document.id, Document.user_defined_name,  DocumentStatus.name, func.date( Assignment.due_date).label('due_date'), func.concat(User.first_name, '  ', User.last_name).label('assigned_user_name') )\
        .filter(Document.archived == False, Assignment.assigned_to_user_id == current_user.id, Document.is_deleted == False , Assignment.status_id not in (3,4) ).all()

    

    
    return render_template('review.html', documents = zip([id for id in range(1, len(documents) + 1) ], documents))






@views.route('/review/assigned_to_user/respond//<int:assignment_id>', methods = ['GET', 'POST'])
@login_required
def assignation_to_me_respond(assignment_id):
    from .models import Document , DocumentStatus,  Assignment, User

    if request.method == 'GET':


        assigned_documents_detail = Assignment.query\
            .join(Document,  Document.id == Assignment.document_id)\
            .join(DocumentStatus, Document.status_id==DocumentStatus.id)\
            .add_columns(Document.id, Document.user_defined_name, DocumentStatus.name, Document.upload_date, Assignment.due_date, Assignment.assigned_comment)\
            .filter(Document.archived == False, Assignment.id == assignment_id, Document.is_deleted == False ).first()
        

        default_due_date  = assigned_documents_detail.due_date.strftime("%Y-%m-%d")



        return render_template('review_extended.html', document = assigned_documents_detail,  due_date = default_due_date)


    elif request.method == "POST":

        
        assignment_document = Assignment.query.filter(Assignment.id == assignment_id ).first()

        document = Document.query.join(Assignment, Assignment.document_id == Document.id).filter(Assignment.id == assignment_id).first()
        
        status_code = 3 if 'accept' in request.form else 4

        document.status_id = status_code


        assignment_document.status_id = status_code

        assignment_document.reviewer_comment = request.form.get('review_comment')

        db.session.commit()


        return redirect(url_for("views.assignation_to_me"))





@views.route('/assign', methods=["GET"])
@login_required
def assignment():
    from .models import Document , DocumentStatus,  Assignment, User

    documents = Document.query\
        .join(DocumentStatus, Document.status_id==DocumentStatus.id)\
        .join(User, Document.user_id == User.id)\
        .add_columns(Document.id, Document.user_defined_name,   DocumentStatus.name )\
        .filter(Document.archived == False, Document.user_id == current_user.id, Document.is_deleted == False ).all()


    print(documents)

    return render_template("assigndocument.html", documents = zip([id for id in range(1, len(documents) + 1) ], documents))



@views.route('/delete/<int:document_id>')
@login_required
def delete_document(document_id):
    from .models import Document,Archive

    try:
        doc_name =  Document.query.filter_by(id = document_id).first()

        doc_name.is_deleted = True
        
        archived_doc_name =  Archive.query.filter_by(document_id = document_id).first()

        aws_util.delete_obj(doc_name.auto_created_name )

        db.session.delete(archived_doc_name)
        db.session.commit()

    except Exception as e:
        print(e)

    return redirect(url_for("views.archived_documents"))




@views.route('/archive_document/<int:document_id>/<int:archive_type>', methods=["GET", "POST"])
@login_required
def update_document_archive(document_id, archive_type):
    from .models import Document, Archive

    

website/templates/archived_documents.html
{% extends "index.html" %} 

{% block title %}
Dashboard
{% endblock %}


{% block header %}
Arxivlənmiş Sənədlər
<script type="text/javascript">
  function openURL(url) {
      // Open the URL in a new tab
      window.open(url, '_blank');
  }

</script>

<style>
    table {
      width: 100%;
      border-collapse: collapse;
    }
  
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
  
    th {
      background-color: #f2f2f2;
      font-weight: bold;
    }
  
    .actions {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 10px;
    }
  
    .actions a {
      color: #333;
      text-decoration: none;
      transition: color 0.3s ease;
      display: flex;
      align-items: center;
    }
  
    .actions a i {
      margin-right: 5px;
    }
  
    .actions a:hover {
      color: #666;
    }
  
    /* Adjust the alignment of other headers */
    th:first-child  {
      text-align: center;
    }
  
    th:not(:first-child), td {
      text-align: center;
      white-space: nowrap;
    }
  </style>
  
  {% endblock %}
  
  {% block body %}
  <table>
    <thead>
      <tr>
        <th>Order</th>
        <th>Başlıq</th>
        <th>Yaradılma Vaxtı</th>
        <th>Arxivlənmə Vaxtı</th>
        <th class="actions">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for order_id, document in documents %}
      <tr>
        <td>{{ order_id }}</td>
        <td>{{ document.user_defined_name }}</td>
        <td>{{ document.Created_Date }}</td>
        <td>{{ document.Archived_Date }}</td>
        <td class="actions">
            <a href="{{ url_for( 'views.update_document_archive', document_id = document.document_id, archive_type = 0) }}"><i class="fas fa-archive"></i> Arxivdən Çıxart</a>
            <a href="{{ url_for( 'views.view_document', document_id = document.document_id) }}" target="_blank"><i class="fas fa-eye"></i> Fayla Bax</a>
            <a href="{{ url_for( 'views.delete_document', document_id = document.document_id) }}"><i class="fas fa-trash-alt"></i> Yüklə</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  
  {% endblock %}
  

website/templates/assignation_details.html
{% extends "index.html" %} 

{% block title %}
Assign Document
{% endblock %}


{% block header %}
Mənim Təyinatlarım
<script type="text/javascript">
  function openURL(url) {
      // Open the URL in a new tab
      window.open(url, '_blank');
  }

</script>

<style>
    table {
      width: 100%;
      border-collapse: collapse;
    }
  
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
  
    th {
      background-color: #f2f2f2;
      font-weight: bold;
    }
  
    .actions {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 10px;
    }
  
    .actions a {
      color: #333;
      text-decoration: none;
      transition: color 0.3s ease;
      display: flex;
      align-items: center;
    }
  
    .actions a i {
      margin-right: 5px;
    }
  
    .actions a:hover {
      color: #666;
    }
  
    /* Adjust the alignment of other headers */
    th:first-child  {
      text-align: center;
    }
  
    th:not(:first-child), td {
      text-align: center;
      white-space: nowrap;
    }
  </style>
  
  {% endblock %}
  
  {% block body %}
  <table>
    <thead>
      <tr>
        <th>Sıralama</th>
        <th>Fayl Adı</th>
        <th>Yaradılma Tarixi</th>
        <th>Status</th>
        <th>Təyin Olunmuş İstifadəçi</th>
        <th class="actions">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for order_id, document in documents %}
      <tr>
        <td>{{ order_id }}</td>
        <td>{{ document.user_defined_name }}</td>
        <td>{{ document.assignment_date }}</td>
        <td>{{ document.name }}</td>
        <td>{{ document.assigned_user_name }}</td>
        <td class="actions">
            <a href="{{ url_for( 'views.assignation_details_details', assignment_id = document.assigment_id) }}"><i class="fas fa-archive"></i>Detallı Bax</a>
            <a href="{{ url_for( 'views.view_document', document_id = document.id) }}" target="_blank"><i class="fas fa-eye"></i>Fayla Bax</a> 
            <a href="{{ url_for( 'views.download_document', document_id = document.id) }}" target="_blank"><i class="fas fa-download"></i>Yüklə</a>
        </td>
      </tr>
      {% endfor %}`
    </tbody>
  </table>
  
  {% endblock %}
  

website/templates/dashboard.html
{% extends "index.html" %} 

{% block title %}
Dashboard
{% endblock %}


{% block header %}
Dashboard
<script type="text/javascript">
  function openURL(url) {
      // Open the URL in a new tab
      window.open(url, '_blank');
  }

</script>

<style>
    table {
      width: 100%;
      border-collapse: collapse;
    }
  
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
  
    th {
      background-color: #f2f2f2;
      font-weight: bold;
    }
  
    .actions {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 10px;
    }
  
    .actions a {
      color: #333;
      text-decoration: none;
      transition: color 0.3s ease;
      display: flex;
      align-items: center;
    }
  
    .actions a i {
      margin-right: 5px;
    }
  
    .actions a:hover {
      color: #666;
    }
  
    /* Adjust the alignment of other headers */
    th:first-child  {
      text-align: center;
    }
  
    th:not(:first-child), td {
      text-align: center;
      white-space: nowrap;
    }
  </style>
  
  {% endblock %}
  
  {% block body %}
  <table>
    <thead>
      <tr>
        <th>Sıralama</th>
        <th>Faylın Adı</th>
        <th>Yaradılma tarixi</th>
        <th>Status</th>
        <th class="actions">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for order_id, document in documents %}
      <tr>
        <td>{{ order_id }}</td>
        <td>{{ document.user_defined_name }}</td>
        <td>{{ document.date }}</td>
        <td>{{ document.name }}</td>
        <td class="actions">
            <a href="{{ url_for( 'views.update_document_archive', document_id = document.id, archive_type = 1) }}"><i class="fas fa-archive"></i> Arxivlə</a>
            <a href="{{ url_for( 'views.view_document', document_id = document.id) }}" target="_blank"><i class="fas fa-eye"></i> Fayla Bax</a>
            <a href="{{ url_for( 'views.download_document', document_id = document.id) }}" target="_blank"><i class="fas fa-download"></i> Yüklə</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  
  {% endblock %}
  

website/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>My Flask Application</title>
    <!-- Link to Bootstrap CSS file -->
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <title> {% block title %}{% endblock %} </title>
    <!-- Custom styles -->


    <style>
        .welcome-message {
            font-family: Arial, sans-serif;
            text-align: center;
            margin-top: 200px;
            font-size: 36px;
            color: #373193;
            margin-bottom: 20px;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
        }
  </style>
    </head>
  <body>
        <div class='dashboard'>
      <div class="dashboard-nav">
          <header><a href="#!" class="menu-toggle">
            <i class="fas fa-bars"></i></a><a href="#" class="brand-logo"><i class="fas fa-file"></i> <span>DMS</span></a>
          </header>
          <nav class="dashboard-nav-list"><a href="/" class="dashboard-nav-item"><i class="fas fa-home"></i> Ana Səhifə </a> 
            <a href="{{ url_for('views.dashboard')}}" class="dashboard-nav-item active"><i class="fas fa-tachometer-alt"></i>Dashboard </a>
              <a href="{{url_for('views.add_document')}}" class="dashboard-nav-item"><i class="fas fa-file-upload"></i> Fayl Yüklə </a>
              <div class='dashboard-nav-dropdown'><a href="#" class="dashboard-nav-item dashboard-nav-dropdown-toggle"><i class="fas fa-photo-video"></i>Faylları İdarə Elə</a>
                  <div class='dashboard-nav-dropdown-menu'>
                        <a href="{{url_for('views.assignment')}}" class="dashboard-nav-dropdown-item">Fayl Təyinatı</a>
                        <a href="{{url_for('views.all_reviews')}}" class="dashboard-nav-dropdown-item">Faylları Nəzərdən Keçir</a>
                        <a href="{{url_for('views.archived_documents')}}" class="dashboard-nav-dropdown-item">Arxivlənmiş Fayllar</a></div>
                  </div>
            <a
                      href="{{url_for('auth.logout')}}" class="dashboard-nav-item"><i class="fas fa-sign-out-alt"></i> Çıxış</a>
          </nav>
      </div>
      <div class='dashboard-app'>
          <header class='dashboard-toolbar'><a href="#!" class="menu-toggle"><i class="fas fa-bars"></i></a></header>
          <div class='dashboard-content'>
              <div class='container' style='width: 80%;'>
                  <div class='card'>
                      <div class='card-header'>
                          <h3>{% block header %} Home Page {% endblock %}</h1>
                      </div>
                      <div class='card-body'>
                        {% block body %} 
                        <div class="welcome-message">
                          Xoş Gəlmisiz {{user_data.first_name}} {{user_data.last_name}} 
                        </div>
                        {% endblock %}
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div> 
  </body>
</html>

website/templates/review.html
{% extends "index.html" %} 

{% block title %}
Assign Document
{% endblock %}


{% block header %}
Mənə Təyin Olunmuş Fayllar
<script type="text/javascript">
  function openURL(url) {
      // Open the URL in a new tab
      window.open(url, '_blank');
  }

</script>

<style>
    table {
      width: 100%;
      border-collapse: collapse;
    }
  
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
  
    th {
      background-color: #f2f2f2;
      font-weight: bold;
    }
  
    .actions {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 10px;
    }
  
    .actions a {
      color: #333;
      text-decoration: none;
      transition: color 0.3s ease;
      display: flex;
      align-items: center;
    }
  
    .actions a i {
      margin-right: 5px;
    }
  
    .actions a:hover {
      color: #666;
    }
  
    /* Adjust the alignment of other headers */
    th:first-child  {
      text-align: center;
    }
  
    th:not(:first-child), td {
      text-align: center;
      white-space: nowrap;
    }
  </style>
  
  {% endblock %}
  
  {% block body %}
  <table>
    <thead>
      <tr>
        <th>Sıralama</th>
        <th>Fayl Adı</th>
        <th>Son Tarix</th>
        <th>Status</th>
        <th>Təyin Etmiş İstifadəçi</th>
        <th class="actions">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for order_id, document in documents %}
      <tr>
        <td>{{ order_id }}</td>
        <td>{{ document.user_defined_name }}</td>
        <td>{{ document.due_date }}</td>
        <td>{{ document.name }}</td>
        <td>{{ document.assigned_user_name }}</td>
        <td class="actions">
            <a href="{{ url_for( 'views.assignation_to_me_respond', assignment_id = document.assignment_id) }}"><i class="fas fa-archive"></i>Cavablandır</a>
            <a href="{{ url_for( 'views.view_document', document_id = document.id) }}" target="_blank"><i class="fas fa-eye"></i>Fayla Bax</a> 
            <a href="{{ url_for( 'views.download_document', document_id = document.id) }}" target="_blank"><i class="fas fa-download"></i>Yüklə</a>
        </td>
      </tr>
      {% endfor %}`
    </tbody>
  </table>
  
  {% endblock %}
  

website/templates/review_extended.html
{% extends "index.html" %} 

{% block title %}
{% endblock %}


{% block header %}
<script>
    function openCalendar() {
      document.getElementById("due_date").click();
    }
</script>

<style>
  body {
      background-color: #f9f9f9;
      color: #373193;
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
  }

  .card {
      background-color: #ffffff;
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 20px;
      margin-top: 20px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  h3 {
      color: #373193;
      font-size: 22px;
      margin-top: 0;
  }

  p {
      color: #373193;
      font-size: 14px;
      margin-bottom: 10px;
  }

  form {
      margin: 0;
  }

  .form-group {
      margin-bottom: 15px;
  }

  .form-group label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
      color: #373193;
  }

  .form-group select,
  .form-group textarea,
  .form-group input[type="text"] {
      width: 100%;
      padding: 8px;
      border: 1px solid #ccc;
      border-radius: 3px;
      resize: vertical;
      background-color: #f9f9f9;
      color: #373193;
      font-size: 14px;
  }

  .form-group button {
      margin-top: 10px;
      padding: 10px 15px;
      border: none;
      border-radius: 3px;
      cursor: pointer;
      font-weight: bold;
      color: #ffffff;
  }

  .form-group .btn-primary {
      background-color: #373193;
  }

  .form-group .btn-secondary {
      background-color: #ffffff;
      color: #373193;
      border: 1px solid #373193;
  }

  .field-group {
      display: flex;
      align-items: center;
      margin-bottom: 10px;
  }

  .field-group label {
      width: 120px;
      margin-right: 10px;
      font-weight: bold;
      color: #373193;
  }

  .field-group .form-control-static {
      padding: 6px 12px;
      background-color: #f9f9f9;
      color: #373193;
      font-size: 14px;
      border: 1px solid #ccc;
      border-radius: 3px;
      flex: 1;
  }

  .field-group .form-control-static.status {
      margin-left: 10px;
  }

  .form-group .form-control {
    background-color: #f9f9f9;
    color: #373193;
    font-size: 14px;
    border: 1px solid #ccc;
    border-radius: 3px;
    padding: 8px;
  }

  
  .view_file  .download_file {
    float: right;
    margin-left: 10px;
  }
  .float-left-button {
    float: right;
    margin-left: 10px;
  }
</style>
{% endblock %}

{% block body %}


<div class="card">
  <form  method="POST">
      <div class="form-group">
          <div class="form-row">
              <div class="col-half">
                  <label for="title">Faylın Adı</label>
                  <input type="text" id="title" name="title" class="form-control-small" value="{{ document.user_defined_name }}"
                      readonly>
              </div>
          </div>
      </div>

      <div class="form-group">
        <label for="comment">Təyin edənin mesajı</label>
        <textarea name="comment" id="assigned_comment" rows="2" cols="40" readonly> {{ document.assigned_comment }} </textarea>
    </div>

      <div class="form-group">
          <label for="creation_date">Faylın Yaradılma Tarixi</label>
          <input type="text" id="creation_date" name="creation_date" class="form-control" value={{document.upload_date}}
              readonly>
      </div>

      
      <div class="form-group">
        <label for="due_date">Deadline Tarixi</label>
        <input type="date" id="due_date" name="due_date" class="form-control" onclick="openCalendar()" value = "{{ due_date }}" readonly>
      </div>


      <div class="form-group">
          <label for="review_comment">Mesaj</label>
          <textarea name="review_comment" id="reviewer_comment" rows="4" cols="50"></textarea>
      </div>

      <div class="form-group">
        <button type="submit" name="accept" class="btn btn-primary">Qəbul Et</button>
        <button type="submit" name="reject" class="btn btn-danger">Rədd Et</button>
        <button type="button" class="btn btn-secondary cancel-button">Ləğv Et</button>

        <button type="button" onclick="window.open('{{ url_for( 'views.view_document', document_id=document.id) }}', '_blank')" class="btn btn-primary float-left-button"><i class="fas fa-eye"></i> Fayla Bax</button>
        <button type="button" onclick="window.open('{{ url_for( 'views.download_document', document_id=document.id) }}', '_blank')" class="btn btn-secondary float-left-button"><i class="fas fa-download"></i> Yüklə</button>
      
    </div>
      
  </form>
</div>



{% endblock %}